name: Run All Required Tests for rAuth0
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v**.**.**

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set Variables
      id: vars
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  docker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Artifactory Login
      run: |
        docker login "${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.ARTIFACTORY_USER }}" -p "${{ secrets.ARTIFACTORY_KEY }}"
    - name: Checkout code
      uses: actions/checkout@v2.3.1
    - name: Build the rAuth0 Docker Environment
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/docker/airflow-rauth0:master .
    - name: Push rAuth0 Docker Image
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/docker/airflow-rauth0:master
